// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDev_H-mfy57ZWvbY1rYp1DIeAFpViOEwI',
    appId: '1:722333056735:web:545fc1fed69a18aa3bf36a',
    messagingSenderId: '722333056735',
    projectId: 'flutter-insta-6c725',
    authDomain: 'flutter-insta-6c725.firebaseapp.com',
    storageBucket: 'flutter-insta-6c725.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWjMKDDbp5bclhUywYn-kS8kuYwhBsXNw',
    appId: '1:722333056735:android:b030d7011f364ff73bf36a',
    messagingSenderId: '722333056735',
    projectId: 'flutter-insta-6c725',
    storageBucket: 'flutter-insta-6c725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt0zC5T4wWzutETY5NMj1BdWnIo-G5tUo',
    appId: '1:722333056735:ios:e83e8e3ebfa994df3bf36a',
    messagingSenderId: '722333056735',
    projectId: 'flutter-insta-6c725',
    storageBucket: 'flutter-insta-6c725.appspot.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt0zC5T4wWzutETY5NMj1BdWnIo-G5tUo',
    appId: '1:722333056735:ios:e83e8e3ebfa994df3bf36a',
    messagingSenderId: '722333056735',
    projectId: 'flutter-insta-6c725',
    storageBucket: 'flutter-insta-6c725.appspot.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDev_H-mfy57ZWvbY1rYp1DIeAFpViOEwI',
    appId: '1:722333056735:web:f585a2e58830c6913bf36a',
    messagingSenderId: '722333056735',
    projectId: 'flutter-insta-6c725',
    authDomain: 'flutter-insta-6c725.firebaseapp.com',
    storageBucket: 'flutter-insta-6c725.appspot.com',
  );
}
